### ISSUE TITLE
Crash on Qemu on first startup

### ISSUE THREAD

**Issue by radl97** [ioi-2023/contestant-vm#35]
![image](https://github.com/ioi-2023/contestant-vm/assets/7879888/5d68a2b3-e498-458d-b7c1-ee3fae90dcc5)

Does it happen on vmware?

**Comment by horcsinbalint** [comment]
It also happened on real hardware

**Comment by horcsinbalint** [comment]
Wayland could probably be the issue: https://askubuntu.com/questions/1410170/gjs-not-responding
The issue is not the same but they might be related.
We should consider moving to Xorg.

**Comment by radl97** [comment]
Stacktrace:

```
Thread 1 (Thread 0x7f3a8babf640 (LWP 2663)):
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139889428133440) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139889428133440) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139889428133440, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f3a8fc42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f3a8fc287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f3a903234ba in mem_error (format=format@entry=0x7f3a9036aa93 "assertion failed: %s") at ../../../glib/gslice.c:1526
#6  0x00007f3a90323a84 in slab_allocator_free_chunk (chunk_size=chunk_size@entry=32, mem=mem@entry=0x55c9918c9a40) at ../../../glib/gslice.c:1401
#7  0x00007f3a90323e0b in magazine_cache_trim (local_allocator=0x7f3a903e7f80 <allocator>, stamp=<optimized out>, ix=<optimized out>) at ../../../glib/gslice.c:723
#8  magazine_cache_push_magazine (ix=<optimized out>, magazine_chunks=<optimized out>, count=51) at ../../../glib/gslice.c:754
#9  0x00007f3a90324229 in thread_memory_magazine2_unload (tmem=0x7f3a7c000b70, tmem=0x7f3a7c000b70, ix=<optimized out>) at ../../../glib/gslice.c:849
#10 g_slice_free1 (mem_size=<optimized out>, mem_block=0x55c9917edd60) at ../../../glib/gslice.c:1165
#11 0x00007f3a902ff5ac in g_main_context_remove_poll_unlocked (context=0x55c991332390, fd=<optimized out>) at ../../../glib/gmain.c:4696
#12 0x00007f3a903003b4 in block_source (source=0x7f3a7c0377b0) at ../../../glib/gmain.c:3313
#13 0x00007f3a90304d61 in g_main_dispatch (context=0x55c991332390) at ../../../glib/gmain.c:3398
#14 g_main_context_dispatch (context=0x55c991332390) at ../../../glib/gmain.c:4137
#15 0x00007f3a9035a258 in g_main_context_iterate.constprop.0 (context=0x55c991332390, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4213
#16 0x00007f3a903042b3 in g_main_loop_run (loop=0x55c991332480) at ../../../glib/gmain.c:4413
#17 0x00007f3a9018b07a in gdbus_shared_thread_func (user_data=0x55c991323d80) at ../../../gio/gdbusprivate.c:282
#18 0x00007f3a90333a51 in g_thread_proxy (data=0x55c99132d800) at ../../../glib/gthread.c:827
#19 0x00007f3a8fc94b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007f3a8fd26a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Something caught a UAF or some memory error, it seems: `slab_allocator_free_chunk`

**Comment by boasbakker** [comment]
The screenshots in #82 might be helpful

**Comment by radl97** [comment]
Although no apparent fixes, the desktop icons vanish with the crash and come back moments later. Tagging low-prio.
