### ISSUE TITLE
`Kate` crashed for me just after closing... ouch

### ISSUE THREAD

**Issue by radl97** [ioi-2023/contestant-vm#47]
```
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:317
#1  0x00007fa1dde4f026 in QByteArray::reallocData(unsigned int, QFlags<QArrayData::AllocationOption>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007fa1dde50230 in QByteArray::append(QByteArray const&) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fa1d007932a in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/ktexteditor/externaltoolsplugin.so
#4  0x00007fa1de01c793 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fa1ddf4db81 in QProcess::readyReadStandardOutput(QProcess::QPrivateSignal)
    () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fa1ddf53f04 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fa1ddf582b9 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fa1ddf4fc25 in QProcess::~QProcess() ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fa1ddf4fd0d in QProcess::~QProcess() ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fa1d0079dd1 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/ktexteditor/externaltoolsplugin.so
#11 0x00007fa1d0079ecd in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/ktexteditor/externaltoolsplugin.so
#12 0x00007fa1de00fa6e in QObjectPrivate::deleteChildren() ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fa1de01a924 in QObject::~QObject() ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fa1d007ac5d in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/ktexteditor/externaltoolsplugin.so
#15 0x000055be319a4634 in ?? ()
#16 0x000055be31964c4f in ?? ()
#17 0x000055be31965af7 in ?? ()
#18 0x000055be3194cf70 in ?? ()
#19 0x000055be31946752 in ?? ()
#20 0x00007fa1dd902d90 in __libc_start_call_main (main=main@entry=0x55be31942ed0, 
    argc=argc@entry=2, argv=argv@entry=0x7ffff15706a8)
```

[kati.tar.gz](https://github.com/ioi-2023/contestant-vm/files/12122705/kati.tar.gz)

**Comment by radl97** [comment]
There have not been other reports. I am assuming it did not reproduce for anyone else.

The file did save, and only the cleanup crashed, so no disruption to the contest. So it is low priority even if it reproduces.
